export const OPTION_HEIGHT = 40;
export const OPTION_GAP = 2;
export const MENU_PADDING = 6;

const MENU_VISIBLE_OPTIONS = 6;

export const MENU_MAX_HEIGHT =
  MENU_VISIBLE_OPTIONS * OPTION_HEIGHT + (MENU_VISIBLE_OPTIONS - 1) * OPTION_GAP + MENU_PADDING * 2;
